locals {
  prefix = "${var.app_name}-${var.environment}"
}

# ── Web bucket (static SPA) ───────────────────────────────────────────────────
# Public read access; serves index.html, JS, and CSS directly from the bucket URL.

resource "oci_objectstorage_bucket" "web" {
  compartment_id = var.compartment_ocid
  namespace      = var.namespace
  name           = "${local.prefix}-web"
  access_type    = "ObjectRead" # public read, no auth required for static assets
  storage_tier   = "Standard"
}

# ── Audiobooks bucket (private Opus files) ────────────────────────────────────
# Private; all access via pre-signed (pre-authenticated) URLs generated by the Function.

resource "oci_objectstorage_bucket" "audiobooks" {
  compartment_id = var.compartment_ocid
  namespace      = var.namespace
  name           = "${local.prefix}-audiobooks"
  access_type    = "NoPublicAccess"
  storage_tier   = "Standard"
}

# ── IAM policy — grants the Object Storage service permission to run lifecycle rules ──
# Without this, OCI cannot execute the DELETE lifecycle action on objects.

resource "oci_identity_policy" "objectstorage_lifecycle" {
  compartment_id = var.compartment_ocid
  name           = "${local.prefix}-objectstorage-lifecycle"
  description    = "Grants Object Storage service permission to manage objects for lifecycle rules."

  statements = [
    "Allow service objectstorage-${var.oci_region} to manage object-family in tenancy",
  ]
}

# ── Lifecycle policy — auto-delete audiobooks after retention window ───────────

resource "oci_objectstorage_object_lifecycle_policy" "audiobooks" {
  namespace = var.namespace
  bucket    = oci_objectstorage_bucket.audiobooks.name

  rules {
    name        = "delete-after-${var.audiobook_retention_days}-days"
    is_enabled  = true
    target      = "objects"
    action      = "DELETE"
    time_amount = var.audiobook_retention_days
    time_unit   = "DAYS"
  }
}

# ── OCI Object Storage namespace data source ───────────────────────────────────
# (namespace is passed in as a variable from the root module's data source)
